FilmothequeBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FilmothequeBundle:Default:index }
    
myapp_accueil:
    pattern:  /
    defaults: { _controller: FilmothequeBundle:Default:index }

