parameters:
#    filmotheque.example.class: Myapp\FilmothequeBundle\Example

services:
#    filmotheque.example:
#        class: %filmotheque.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
