FilmothequeBundle:
    resource: "@FilmothequeBundle/Resources/config/routing.yml"
    prefix:   /myapp

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
